### ISSUE TITLE
php 5.6 compatibility

### ISSUE THREAD

**Issue by tehnotronic** [ThaDafinser/Piwik-LdapVisitorInfo#10]
Hi,

Is there a reason why PHP 5.6 is not supported, like using some newer functions etc?
If it would work with 5.6, can you please allow it in plugin.json?

Thank you

**Comment by ThaDafinser** [comment]
> Is there a reason why PHP 5.6 is not supported, like using some newer functions etc?

No new functions are used. But i don't wanna support 5.6 and i dismiss 5.* support in all new major version of my packages.

> If it would work with 5.6, can you please allow it in plugin.json?

Because of the reason above, sadly no. You can download the zip, modify the requirements and deploy it by hand.
