### ISSUE TITLE
thumbnailphoto setting only INT

### ISSUE THREAD

**Issue by tehnotronic** [ThaDafinser/Piwik-LdapVisitorInfo#11]
On the general settings page, the thumbnailphoto field only accepts integer, it should be text?

```
        $this->visitorAvatarField = $this->makeSetting('visitorAvatarField', 'thumbnailphoto', FieldConfig::TYPE_INT, function (FieldConfig $field) {
            $field->title = 'Avatar field name';
            $field->uiControl = FieldConfig::UI_CONTROL_TEXT;
            $field->description = 'In AD it\'s normally thumbnailphoto';
        });
```
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/blob/master/SystemSettings.php#L57

**Comment by ThaDafinser** [comment]
Thank you for the report.

It's fixed in `3.0.1` https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/releases/tag/v3.0.1
