### ISSUE TITLE
No visitor description (name etc.) displayed, only avatar

### ISSUE THREAD

**Issue by tehnotronic** [ThaDafinser/Piwik-LdapVisitorInfo#12]
On the visitor profile page I got thumbnailphoto avatar working, but other info like displayname, sn, mail is not displayed. 

On the API the output is correct: 
https://localhost/index.php?date=2017-03-14&module=API&action=index&visitorId=a121b05e7426fa8f&idSite=12&period=day&method=Live.getVisitorProfile&format=XML&expanded=1&token_auth=xxx

```
<result>
...
<visitorAvatar>data:image/jpeg;base64,/9j
...
//Z</visitorAvatar>
<visitorDescription>displayname: John Smith;
givenname: John;
sn: Smith;
mail: john.smith@company.tld</visitorDescription></result>
```

![screenshot_90](https://cloud.githubusercontent.com/assets/6266189/23896484/42bebc4e-08b2-11e7-93e8-742570321183.png)

**Comment by ThaDafinser** [comment]
@tehnotronic it's currently only displayed as a img info
![image](https://cloud.githubusercontent.com/assets/533017/23898605/da1dea70-08b1-11e7-911d-0fd06e89d3be.png)

**Comment by tehnotronic** [comment]
You are correct, my mistake :)
