### ISSUE TITLE
Not able to fetch visitor's data

### ISSUE THREAD

**Issue by kristopherkrost** [ThaDafinser/Piwik-LdapVisitorInfo#4]
Hi Martin, I am new to PIWIK and LDAP as well. I am trying to fetch visitor email id from the form filled while downloading White Paper, Case Studies (or) enquiry, to visitor's profile in PIWIK. I have installed LDAPVisitorInfo plugin and created custom variables also. The code looks like this:

  var _paq = _paq || [];
  // you can set up to 5 custom variables for each visitor
  _paq.push(["setCustomVariable", 1, "email", "<?php echo $email; ?>", "visit"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.proretention.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();

Now the actual problem is, email id is not fetched to visitor's profile, instead it shows blank. What can be the error. 

Any help appreciated!

Thanks in advance.
![email-blank-visitorlog](https://cloud.githubusercontent.com/assets/11311579/6482182/915b3a9c-c289-11e4-8228-ad573353a89b.PNG)

![email-blank-visitorprofile](https://cloud.githubusercontent.com/assets/11311579/6482204/b279194c-c289-11e4-83db-f062de5016e2.PNG)

**Comment by ThaDafinser** [comment]
You should see something like `email : your@mail.com` in the profile.
Otherwise your variable is not tracked correctly (and so everything else wont work).

**Comment by kristopherkrost** [comment]
Thats correct, and if LDAPConnection plugin also need to be installed, then Please help me in how to install this LDAP service on server. I am new to this. I have installed LDAPConnection plugin and I have filled the text box with the default values suggested beside.

**Comment by kristopherkrost** [comment]
I have searched a lot articles, discussions on installing LDAP service into server. With no luck I have found nothing. Help me out in installing, establishing LDAP connection and let LDAPVisitorInfo shall work fine.

![piwik - super admin error](https://cloud.githubusercontent.com/assets/11311579/6503111/e44c0be8-c34f-11e4-889e-1fc56d648309.PNG)

**Comment by ThaDafinser** [comment]
@kristopherkrost your PHP installation does not have LDAP support.
Please install the extension.

http://php.net/manual/en/ldap.installation.php

**Comment by kristopherkrost** [comment]
Thank you Martin, We have a shared hosting from GoDaddy and there I found no options on updating or any terminal where i can run those codes. Sorry to bother you, Please help!

**Comment by ThaDafinser** [comment]
@kristopherkrost i dont know your hosting, but maye check this https://support.godaddy.com/help/article/12036/enabling-php-modules-on-your-shared-hosting-account?locale=de-DE&countrysite=de

**Comment by kristopherkrost** [comment]
You were right, Thank you Martin. It is the server issue, LDAP services was not enabled in my hosting plan.
