### ISSUE TITLE
Not picking up pictures off AD

### ISSUE THREAD

**Issue by breaup** [ThaDafinser/Piwik-LdapVisitorInfo#6]
so I added my custom variables
      _paq.push(['setCustomVariable', '1',
      'username',
      '<%=lblCurrentUserSamAccountName.Text%>',
        'visit'
      ]);

Basically my .net code is picking up the username off ad and binding the label, and it shows up in the Visitor logs like it's suppose to,
Name of the custom variable is set to username
avatar field name thumbnailphoto
display field name displayname

When I click view visitor profile I still do not see the thumbnail. Any ideas ?

**Comment by ThaDafinser** [comment]
Sorry for getting back so late to this.

It should work, if everything is configured correctly.

If you still have issues, please reopen this issue.
