### ISSUE TITLE
Not compatible with piwik 3.0.0

### ISSUE THREAD

**Issue by tehnotronic** [ThaDafinser/Piwik-LdapVisitorInfo#8]
This plugin is not compatible with piwik 3.0.0, please update it, this is a great and useful plugin!

**Comment by cjsfj** [comment]
+1. Agree! Would love to see this updated.

**Comment by ThaDafinser** [comment]
I'm waiting for https://github.com/piwik/piwik/issues/6324 to be resolved.

After that i can check the plugin

**Comment by AlexR1** [comment]
Hello
is there any progress? (with Piwik 3.0.2 and all)

Thanks!

**Comment by ThaDafinser** [comment]
@tehnotronic @AlexR1 pls download those 2 branches and install them
https://github.com/ThaDafinser/Piwik-LdapConnection/tree/feature/piwik3
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/tree/feature/piwik3

I got it working with a fresh installation - can you verify that? (Maybe you need to update your configuration!)

**Comment by ThaDafinser** [comment]
Those 3 ***plugins should work now with all with `piwik 3`*** :tada: 

I tried them all local on a fresh installation successfull now, so please test them carefully and provide me some feedback!

# Installation
Download the ZIP from GitHub and install it by hand, see https://piwik.org/faq/plugins/faq_21/

## LdapVisitorInfo (requires both plugins)
https://github.com/ThaDafinser/Piwik-LdapVisitorInfo/tree/feature/piwik3
https://github.com/ThaDafinser/Piwik-LdapConnection/tree/feature/piwik3

## Ip2Hostname
https://github.com/ThaDafinser/Piwik-Ip2Hostname/tree/feature/piwik3

## IntranetGeoIp
https://github.com/ThaDafinser/Piwik-IntranetGeoIP/tree/feature/piwik3

**Comment by AlexR1** [comment]
Hi, 
Although I didn't know I should uninstall first the old version, 
I eventually succeeded to install the new one.

it seems to be working (I am still waiting for more users to login)!

thank you very much!
YOU ARE THE MAN!

**Comment by ThaDafinser** [comment]
Just released the package - should be soon available over the marketplace!
